### ISSUE TITLE
遇到两个问题如下

### ISSUE THREAD

**Issue by wennjie** [weexext/ucar-weex-core#1]
cli 打包ok， 但是copy时不能copy到app-main-assets下

weex-sdk16 -assets 下无main.js

**Comment by cuichenxi** [comment]
qq群:581541501

**Comment by coreycao** [comment]
@wennjie 
你好，感谢关注。
main.js 文件已经提交到仓库 ucar-weex-core，可在相应目录下看到；
是在使用 AwesomeProject 项目执行 copy 命令时失败了吗？
